export const SKILL_LEVELS = [
	{ id: 1, name: "Beginner" },
	{ id: 2, name: "Novice" },
	{ id: 3, name: "Intermediate" },
	{ id: 4, name: "Advanced" },
	{ id: 5, name: "Chef" },
];

export const FLAVOR_PREFERENCES = [
	{ id: 1, name: "Nutritious" },
	{ id: 2, name: "Guilt-free" },
	{ id: 3, name: "Balanced" },
	{ id: 4, name: "Indulgent" },
	{ id: 5, name: "Delicious" },
];

export const CUISINES = [
	"American",
	"Mexican",
	"Caribbean",
	"Brazilian",
	"Argentinian",
	"Chilean",
	"Peruvian",
	"Colombian",
	"Ecuadorian",
	"Venezuelan",
	"Bolivian",
	"Italian",
	"French",
	"Spanish",
	"Portuguese",
	"German",
	"Dutch",
	"British",
	"Nordic",
	"Greek",
	"Russian",
	"Polish",
	"Czech",
	"Hungarian",
	"Balkan",
	"Mediterranean",
	"Middle Eastern",
	"West African",
	"Central African",
	"Southern African",
	"East African",
	"Chinese",
	"Japanese",
	"Korean",
	"Vietnamese",
	"Thai",
	"Malay",
	"Indonesian",
	"Filipino",
	"Indian",
	"Australian",
	"Pacific",
	"International",
];

export const API_BASE_URLS = {
	RECIPE: "https://whatsfordinner-m0d2.onrender.com/api/recipe",
	IMAGE: "https://whatsfordinner-m0d2.onrender.com/api/image?dish=",
};
