// Maps every country to a cuisine region for world map selection
// You can adjust the cuisine assignment as needed
// Comprehensive mapping of all world countries to cuisine regions
// Cuisine types are expanded for global coverage
export const CUISINE_COUNTRY_CODES = [
	// North America
	{ country: "US", cuisine: "American" },
	{ country: "CA", cuisine: "American" },
	{ country: "MX", cuisine: "Mexican" },
	// Central America & Caribbean
	{ country: "GT", cuisine: "Mexican" },
	{ country: "BZ", cuisine: "Mexican" },
	{ country: "SV", cuisine: "Mexican" },
	{ country: "HN", cuisine: "Mexican" },
	{ country: "NI", cuisine: "Mexican" },
	{ country: "CR", cuisine: "Mexican" },
	{ country: "PA", cuisine: "Mexican" },
	{ country: "CU", cuisine: "Caribbean" },
	{ country: "JM", cuisine: "Caribbean" },
	{ country: "HT", cuisine: "Caribbean" },
	{ country: "DO", cuisine: "Caribbean" },
	{ country: "BS", cuisine: "Caribbean" },
	// South America
	{ country: "BR", cuisine: "Brazilian" },
	{ country: "AR", cuisine: "Argentinian" },
	{ country: "CL", cuisine: "Chilean" },
	{ country: "PE", cuisine: "Peruvian" },
	{ country: "CO", cuisine: "Colombian" },
	{ country: "EC", cuisine: "Ecuadorian" },
	{ country: "VE", cuisine: "Venezuelan" },
	{ country: "UY", cuisine: "Argentinian" },
	{ country: "PY", cuisine: "Argentinian" },
	{ country: "BO", cuisine: "Bolivian" },
	{ country: "SR", cuisine: "Caribbean" },
	// Europe
	{ country: "IT", cuisine: "Italian" },
	{ country: "FR", cuisine: "French" },
	{ country: "GF", cuisine: "French" },
	{ country: "CH", cuisine: "French" },
	{ country: "BE", cuisine: "French" },
	{ country: "LU", cuisine: "French" },
	{ country: "ES", cuisine: "Spanish" },
	{ country: "PT", cuisine: "Portuguese" },
	{ country: "DE", cuisine: "German" },
	{ country: "AT", cuisine: "German" },
	{ country: "NL", cuisine: "Dutch" },
	{ country: "IE", cuisine: "British" },
	{ country: "GB", cuisine: "British" },
	{ country: "DK", cuisine: "Nordic" },
	{ country: "SE", cuisine: "Nordic" },
	{ country: "NO", cuisine: "Nordic" },
	{ country: "FI", cuisine: "Nordic" },
	{ country: "IS", cuisine: "Nordic" },
	{ country: "GR", cuisine: "Greek" },
	{ country: "CY", cuisine: "Greek" },
	{ country: "RU", cuisine: "Russian" },
	{ country: "UA", cuisine: "Russian" },
	{ country: "PL", cuisine: "Polish" },
	{ country: "CZ", cuisine: "Czech" },
	{ country: "SK", cuisine: "Czech" },
	{ country: "HU", cuisine: "Hungarian" },
	{ country: "RO", cuisine: "Balkan" },
	{ country: "BG", cuisine: "Balkan" },
	{ country: "RS", cuisine: "Balkan" },
	{ country: "HR", cuisine: "Balkan" },
	{ country: "SI", cuisine: "Balkan" },
	{ country: "ME", cuisine: "Balkan" },
	{ country: "MK", cuisine: "Balkan" },
	{ country: "AL", cuisine: "Balkan" },
	{ country: "BA", cuisine: "Balkan" },
	{ country: "MD", cuisine: "Balkan" },
	{ country: "BY", cuisine: "Russian" },
	{ country: "EE", cuisine: "Nordic" },
	{ country: "LV", cuisine: "Nordic" },
	{ country: "LT", cuisine: "Nordic" },
	// Middle East & North Africa
	{ country: "IL", cuisine: "Mediterranean" },
	{ country: "TR", cuisine: "Mediterranean" },
	{ country: "LB", cuisine: "Mediterranean" },
	{ country: "JO", cuisine: "Mediterranean" },
	{ country: "EG", cuisine: "Mediterranean" },
	{ country: "MA", cuisine: "Mediterranean" },
	{ country: "DZ", cuisine: "Mediterranean" },
	{ country: "TN", cuisine: "Mediterranean" },
	{ country: "LY", cuisine: "Mediterranean" },
	{ country: "SY", cuisine: "Mediterranean" },
	{ country: "IQ", cuisine: "Middle Eastern" },
	{ country: "IR", cuisine: "Middle Eastern" },
	{ country: "SA", cuisine: "Middle Eastern" },
	{ country: "AE", cuisine: "Middle Eastern" },
	{ country: "QA", cuisine: "Middle Eastern" },
	{ country: "KW", cuisine: "Middle Eastern" },
	{ country: "OM", cuisine: "Middle Eastern" },
	{ country: "YE", cuisine: "Middle Eastern" },
	{ country: "PS", cuisine: "Mediterranean" },
	// Africa
	{ country: "NG", cuisine: "West African" },
	{ country: "GH", cuisine: "West African" },
	{ country: "CI", cuisine: "West African" },
	{ country: "SN", cuisine: "West African" },
	{ country: "ML", cuisine: "West African" },
	{ country: "BF", cuisine: "West African" },
	{ country: "NE", cuisine: "West African" },
	{ country: "TG", cuisine: "West African" },
	{ country: "BJ", cuisine: "West African" },
	{ country: "SL", cuisine: "West African" },
	{ country: "LR", cuisine: "West African" },
	{ country: "GM", cuisine: "West African" },
	{ country: "GN", cuisine: "West African" },
	{ country: "GW", cuisine: "West African" },
	{ country: "CM", cuisine: "Central African" },
	{ country: "GA", cuisine: "Central African" },
	{ country: "GQ", cuisine: "Central African" },
	{ country: "CG", cuisine: "Central African" },
	{ country: "CD", cuisine: "Central African" },
	{ country: "AO", cuisine: "Central African" },
	{ country: "ST", cuisine: "Central African" },
	{ country: "SZ", cuisine: "Southern African" },
	{ country: "LS", cuisine: "Southern African" },
	{ country: "ZA", cuisine: "Southern African" },
	{ country: "NA", cuisine: "Southern African" },
	{ country: "BW", cuisine: "Southern African" },
	{ country: "ZM", cuisine: "Southern African" },
	{ country: "MW", cuisine: "Southern African" },
	{ country: "MZ", cuisine: "Southern African" },
	{ country: "ZW", cuisine: "Southern African" },
	{ country: "KE", cuisine: "East African" },
	{ country: "UG", cuisine: "East African" },
	{ country: "TZ", cuisine: "East African" },
	{ country: "RW", cuisine: "East African" },
	{ country: "BI", cuisine: "East African" },
	{ country: "ET", cuisine: "East African" },
	{ country: "SO", cuisine: "East African" },
	{ country: "DJ", cuisine: "East African" },
	{ country: "ER", cuisine: "East African" },
	{ country: "SD", cuisine: "East African" },
	{ country: "SS", cuisine: "East African" },
	{ country: "MG", cuisine: "East African" },
	{ country: "MU", cuisine: "East African" },
	{ country: "SC", cuisine: "East African" },
	// Asia
	{ country: "CN", cuisine: "Chinese" },
	{ country: "JP", cuisine: "Japanese" },
	{ country: "KR", cuisine: "Korean" },
	{ country: "VN", cuisine: "Vietnamese" },
	{ country: "TH", cuisine: "Thai" },
	{ country: "MY", cuisine: "Malay" },
	{ country: "SG", cuisine: "Malay" },
	{ country: "ID", cuisine: "Indonesian" },
	{ country: "PH", cuisine: "Filipino" },
	{ country: "IN", cuisine: "Indian" },
	{ country: "PK", cuisine: "Indian" },
	{ country: "BD", cuisine: "Indian" },
	{ country: "LK", cuisine: "Indian" },
	{ country: "NP", cuisine: "Indian" },
	{ country: "BT", cuisine: "Indian" },
	{ country: "MM", cuisine: "Thai" },
	{ country: "KH", cuisine: "Thai" },
	{ country: "LA", cuisine: "Thai" },
	{ country: "MN", cuisine: "Chinese" },
	{ country: "TW", cuisine: "Chinese" },
	{ country: "HK", cuisine: "Chinese" },
	{ country: "MO", cuisine: "Chinese" },
	// Oceania
	{ country: "AU", cuisine: "Australian" },
	{ country: "NZ", cuisine: "Australian" },
	{ country: "FJ", cuisine: "Pacific" },
	{ country: "PG", cuisine: "Pacific" },
	{ country: "SB", cuisine: "Pacific" },
	{ country: "VU", cuisine: "Pacific" },
	{ country: "NC", cuisine: "Pacific" },
	{ country: "WS", cuisine: "Pacific" },
	{ country: "TO", cuisine: "Pacific" },
	{ country: "TV", cuisine: "Pacific" },
	{ country: "KI", cuisine: "Pacific" },
	{ country: "NR", cuisine: "Pacific" },
	{ country: "MH", cuisine: "Pacific" },
	{ country: "FM", cuisine: "Pacific" },
	{ country: "PW", cuisine: "Pacific" },
];
